// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import Tutorial from "@/components/custom/Tutorial";
import { DonationButton } from "@/components/custom/DonationButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fé Digital - Sua Jornada Espiritual",
  description: "App cristão para crescimento espiritual, oração e comunidade",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-inter antialiased`}
        style={{ fontFamily: 'var(--font-inter), var(--font-geist-sans), system-ui, sans-serif' }}
      >
        {children}
        <Tutorial />
        <DonationButton />
      </body>
    </html>
  );
}
